import React, { useState, useEffect, useRef } from 'react';
import {
  Box, Grid, Card, CardContent, Typography, Button, Chip, Avatar,
  CircularProgress, LinearProgress, Divider, Switch, FormControlLabel,
  Tooltip, Alert, Collapse, Dialog, DialogTitle, DialogContent,
  DialogActions, IconButton, TextField, Skeleton, Badge
} from '@mui/material';
import {
  AutoAwesomeRounded, SendRounded, PeopleRounded, CheckCircleRounded,
  EmailRounded, ErrorRounded, VisibilityRounded, CloseRounded,
  BoltRounded, TrendingUpRounded, LocalOfferRounded, MarkEmailReadRounded
} from '@mui/icons-material';
import { useSnackbar } from 'notistack';
import { autoCampaignAPI, customerAPI } from '../services/api';
import { formatCurrency } from '../utils/format';

const STEP_COLORS = { idle: '#9CA3AF', running: '#5B4CF5', done: '#22C55E', error: '#EF4444' };

export default function AICampaign() {
  const [segments, setSegments] = useState([]);
  const [segmentsLoading, setSegmentsLoading] = useState(true);
  const [selectedSegment, setSelectedSegment] = useState(null);
  const [sendRealEmail, setSendRealEmail] = useState(false);
  const [maxCustomers, setMaxCustomers] = useState(10);
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState(null);
  const [steps, setSteps] = useState([]);
  const [previewCustomer, setPreviewCustomer] = useState(null);
  const [previewData, setPreviewData] = useState(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [customers, setCustomers] = useState([]);
  const [offerDialog, setOfferDialog] = useState(null);
  const { enqueueSnackbar } = useSnackbar();
  const stepRef = useRef([]);

  useEffect(() => {
    autoCampaignAPI.getSegments()
      .then(r => setSegments(r.data.data))
      .catch(e => enqueueSnackbar(e.message, { variant: 'error' }))
      .finally(() => setSegmentsLoading(false));

    customerAPI.getAll({ limit: 20 })
      .then(r => setCustomers(r.data.data))
      .catch(() => {});
  }, []);

  const addStep = (label, status = 'running', detail = '') => {
    const step = { id: Date.now() + Math.random(), label, status, detail, time: new Date() };
    stepRef.current = [...stepRef.current, step];
    setSteps([...stepRef.current]);
    return step;
  };

  const updateLastStep = (status, detail = '') => {
    const arr = [...stepRef.current];
    if (arr.length > 0) {
      arr[arr.length - 1] = { ...arr[arr.length - 1], status, detail };
    }
    stepRef.current = arr;
    setSteps([...arr]);
  };

  const handleGenerate = async () => {
    if (!selectedSegment) return enqueueSnackbar('Please select an audience segment', { variant: 'warning' });

    setRunning(true);
    setResult(null);
    stepRef.current = [];
    setSteps([]);

    addStep(`Reading ${selectedSegment.title} customers from database…`);
    await delay(600);
    updateLastStep('done', `Found ${selectedSegment.count} customers`);

    addStep('Fetching order history for each customer…');
    await delay(500);
    updateLastStep('done', 'Order history loaded');

    addStep('Calling Gemini AI to analyze customer data…');
    await delay(400);
    updateLastStep('running', 'Generating personalized offers per customer…');

    try {
      const res = await autoCampaignAPI.generate({
        segmentKey: selectedSegment.key,
        sendRealEmail,
        maxCustomers,
        campaignName: `AI Campaign — ${selectedSegment.title}`
      });

      updateLastStep('done', `${res.data.data.results.length} personalized offers generated by Gemini`);

      addStep(sendRealEmail ? 'Sending real emails via SMTP…' : 'Simulating email delivery…');
      await delay(400);
      updateLastStep('done',
        sendRealEmail
          ? `${res.data.data.summary.realEmailsSent} emails sent`
          : `${res.data.data.summary.delivered} deliveries simulated`
      );

      addStep('Saving campaign & communication logs to database…');
      await delay(300);
      updateLastStep('done', `Campaign "${res.data.data.campaign.name}" saved`);

      addStep('Campaign complete!', 'done', `✅ ${res.data.data.summary.total} customers reached`);

      setResult(res.data.data);
      enqueueSnackbar(`🎉 AI Campaign sent to ${res.data.data.summary.total} customers!`, { variant: 'success' });
    } catch (err) {
      updateLastStep('error', err.message);
      addStep('Campaign failed', 'error', err.message);
      enqueueSnackbar(err.message, { variant: 'error' });
    } finally {
      setRunning(false);
    }
  };

  const handlePreview = async (customer) => {
    setPreviewCustomer(customer);
    setPreviewData(null);
    setPreviewLoading(true);
    setPreviewOpen(true);
    try {
      const res = await autoCampaignAPI.previewOffer({
        customerId: customer._id,
        segmentKey: selectedSegment?.key || 'all'
      });
      setPreviewData(res.data.data);
    } catch (err) {
      enqueueSnackbar(err.message, { variant: 'error' });
      setPreviewOpen(false);
    } finally {
      setPreviewLoading(false);
    }
  };

  const seg = selectedSegment;
  const AVATAR_COLORS = ['#5B4CF5','#9B59FF','#3B82F6','#22C55E','#F59E0B','#EF4444'];

  return (
    <Box>
      {/* Hero Header */}
      <Card sx={{
        mb: 3, overflow: 'hidden', position: 'relative',
        background: 'linear-gradient(135deg, #1a0533 0%, #2d1065 50%, #0f2b5e 100%)'
      }}>
        <Box sx={{ position: 'absolute', right: -60, top: -60, width: 280, height: 280, borderRadius: '50%', background: 'rgba(155,89,255,0.12)' }} />
        <Box sx={{ position: 'absolute', right: 120, bottom: -80, width: 200, height: 200, borderRadius: '50%', background: 'rgba(91,76,245,0.1)' }} />
        <CardContent sx={{ p: 3.5, position: 'relative' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1.5 }}>
            <Box sx={{ width: 40, height: 40, borderRadius: 2, background: 'rgba(255,255,255,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <AutoAwesomeRounded sx={{ color: '#fff', fontSize: 22 }} />
            </Box>
            <Box>
              <Typography variant="overline" sx={{ color: 'rgba(255,255,255,0.6)', letterSpacing: '0.12em', fontSize: '0.68rem' }}>
                POWERED BY GOOGLE GEMINI AI
              </Typography>
              <Typography variant="h5" sx={{ color: '#fff', fontWeight: 800, lineHeight: 1.2 }}>
                AI Campaign Engine
              </Typography>
            </Box>
          </Box>
          <Typography variant="body2" sx={{ color: 'rgba(255,255,255,0.75)', maxWidth: 520, lineHeight: 1.7, mb: 2 }}>
            Gemini reads each customer's purchase history, spending patterns, and favourite categories — then writes a <strong style={{color:'#C4B5FD'}}>unique personalized offer</strong> for every single customer and delivers it automatically.
          </Typography>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            {[
              { icon: '🧠', label: 'AI reads real customer data' },
              { icon: '✍️', label: 'Unique offer per customer' },
              { icon: '📧', label: 'Auto email delivery' },
              { icon: '📊', label: 'Live results tracked' }
            ].map((f, i) => (
              <Box key={i} sx={{ display: 'flex', alignItems: 'center', gap: 0.75, bgcolor: 'rgba(255,255,255,0.1)', borderRadius: 2, px: 1.5, py: 0.75 }}>
                <Typography sx={{ fontSize: '1rem' }}>{f.icon}</Typography>
                <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.85)', fontWeight: 600, fontSize: '0.72rem' }}>{f.label}</Typography>
              </Box>
            ))}
          </Box>
        </CardContent>
      </Card>

      <Grid container spacing={3}>
        {/* LEFT — Config panel */}
        <Grid item xs={12} lg={5}>
          {/* Step 1 — Segment */}
          <Card sx={{ mb: 2.5 }}>
            <CardContent sx={{ p: 2.5 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                <Box sx={{ width: 24, height: 24, borderRadius: '50%', bgcolor: 'primary.main', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Typography sx={{ color: '#fff', fontSize: '0.72rem', fontWeight: 800 }}>1</Typography>
                </Box>
                <Typography variant="subtitle1" fontWeight={700}>Choose Audience Segment</Typography>
              </Box>

              {segmentsLoading ? (
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                  {Array(4).fill(0).map((_, i) => <Skeleton key={i} height={56} sx={{ borderRadius: 2 }} />)}
                </Box>
              ) : (
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                  {segments.map(seg => (
                    <Box
                      key={seg.key}
                      onClick={() => setSelectedSegment(seg)}
                      sx={{
                        display: 'flex', alignItems: 'center', gap: 1.5, p: 1.5,
                        border: '2px solid',
                        borderColor: selectedSegment?.key === seg.key ? seg.color : 'divider',
                        borderRadius: 2.5, cursor: 'pointer',
                        bgcolor: selectedSegment?.key === seg.key ? `${seg.color}0a` : 'transparent',
                        transition: 'all 0.15s',
                        '&:hover': { borderColor: seg.color, bgcolor: `${seg.color}06` }
                      }}
                    >
                      <Box sx={{ width: 38, height: 38, borderRadius: 2, bgcolor: `${seg.color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', flexShrink: 0 }}>
                        {seg.icon}
                      </Box>
                      <Box sx={{ flex: 1, minWidth: 0 }}>
                        <Typography variant="body2" fontWeight={700} noWrap>{seg.title}</Typography>
                        <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.7rem' }} noWrap>{seg.description}</Typography>
                      </Box>
                      <Chip label={`${seg.count} customers`} size="small"
                        sx={{ bgcolor: `${seg.color}18`, color: seg.color, fontWeight: 700, fontSize: '0.68rem', flexShrink: 0 }} />
                    </Box>
                  ))}
                </Box>
              )}
            </CardContent>
          </Card>

          {/* Step 2 — Options */}
          <Card sx={{ mb: 2.5 }}>
            <CardContent sx={{ p: 2.5 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                <Box sx={{ width: 24, height: 24, borderRadius: '50%', bgcolor: 'primary.main', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Typography sx={{ color: '#fff', fontSize: '0.72rem', fontWeight: 800 }}>2</Typography>
                </Box>
                <Typography variant="subtitle1" fontWeight={700}>Configure Options</Typography>
              </Box>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <TextField
                  label="Max customers to reach"
                  type="number"
                  size="small"
                  value={maxCustomers}
                  onChange={e => setMaxCustomers(Math.max(1, Math.min(50, +e.target.value)))}
                  helperText="1–50 customers (each gets a unique AI-written offer)"
                  inputProps={{ min: 1, max: 50 }}
                  fullWidth
                />

                <Box sx={{ p: 2, border: '1px solid', borderColor: sendRealEmail ? 'success.main' : 'divider', borderRadius: 2, transition: 'all 0.2s', bgcolor: sendRealEmail ? 'rgba(34,197,94,0.04)' : 'transparent' }}>
                  <FormControlLabel
                    control={
                      <Switch
                        checked={sendRealEmail}
                        onChange={e => setSendRealEmail(e.target.checked)}
                        color="success"
                      />
                    }
                    label={
                      <Box>
                        <Typography variant="body2" fontWeight={700}>Send Real Emails</Typography>
                        <Typography variant="caption" color="text.secondary">
                          {sendRealEmail ? 'Will send actual emails via configured SMTP/Gmail' : 'Simulate only — no real emails sent'}
                        </Typography>
                      </Box>
                    }
                    sx={{ m: 0 }}
                  />
                  {sendRealEmail && (
                    <Alert severity="info" sx={{ mt: 1.5, py: 0.5, fontSize: '0.75rem' }}>
                      Configure Gmail/SMTP in Settings → Email Configuration first.
                    </Alert>
                  )}
                </Box>
              </Box>
            </CardContent>
          </Card>

          {/* Step 3 — Launch */}
          <Card sx={{ background: !selectedSegment ? 'background.paper' : 'linear-gradient(135deg,rgba(91,76,245,0.04),rgba(155,89,255,0.04))', border: !selectedSegment ? undefined : '1px solid rgba(91,76,245,0.2)' }}>
            <CardContent sx={{ p: 2.5 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                <Box sx={{ width: 24, height: 24, borderRadius: '50%', bgcolor: 'primary.main', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Typography sx={{ color: '#fff', fontSize: '0.72rem', fontWeight: 800 }}>3</Typography>
                </Box>
                <Typography variant="subtitle1" fontWeight={700}>Launch AI Campaign</Typography>
              </Box>

              {selectedSegment && (
                <Box sx={{ p: 1.5, bgcolor: 'background.default', borderRadius: 2, mb: 2 }}>
                  <Typography variant="caption" color="text.secondary" fontWeight={600} sx={{ textTransform: 'uppercase', letterSpacing: '0.06em', display: 'block', mb: 0.5 }}>
                    Ready to launch
                  </Typography>
                  <Typography variant="body2"><strong>{selectedSegment.icon} {selectedSegment.title}</strong></Typography>
                  <Typography variant="caption" color="text.secondary">
                    Up to {maxCustomers} customers · {sendRealEmail ? 'Real email delivery' : 'Simulated delivery'} · Gemini AI offers
                  </Typography>
                </Box>
              )}

              <Button
                variant="contained"
                fullWidth
                size="large"
                startIcon={running ? <CircularProgress size={18} color="inherit" /> : <BoltRounded />}
                onClick={handleGenerate}
                disabled={running || !selectedSegment}
                sx={{
                  py: 1.5, fontWeight: 800, fontSize: '0.95rem',
                  background: 'linear-gradient(135deg, #5B4CF5, #9B59FF)',
                  '&:hover': { background: 'linear-gradient(135deg, #4A3DE0, #8845F0)', transform: 'translateY(-1px)', boxShadow: '0 8px 24px rgba(91,76,245,0.4)' },
                  '&:disabled': { background: '#E5E7EB', color: '#9CA3AF' },
                  transition: 'all 0.2s'
                }}
              >
                {running ? 'Gemini is working…' : '🚀 Generate & Send AI Campaign'}
              </Button>
            </CardContent>
          </Card>

          {/* Preview customer offer */}
          {customers.length > 0 && !running && !result && (
            <Card sx={{ mt: 2.5 }}>
              <CardContent sx={{ p: 2.5 }}>
                <Typography variant="subtitle2" fontWeight={700} mb={1.5}>
                  🔍 Preview AI offer for a customer
                </Typography>
                <Typography variant="caption" color="text.secondary" display="block" mb={1.5}>
                  See exactly what Gemini will generate before launching
                </Typography>
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                  {customers.slice(0, 4).map((c, i) => (
                    <Box key={c._id} sx={{ display: 'flex', alignItems: 'center', gap: 1.5, p: 1.2, border: '1px solid', borderColor: 'divider', borderRadius: 2 }}>
                      <Avatar sx={{ width: 28, height: 28, fontSize: '0.75rem', fontWeight: 800, bgcolor: AVATAR_COLORS[i % AVATAR_COLORS.length], flexShrink: 0 }}>
                        {c.name.charAt(0)}
                      </Avatar>
                      <Box sx={{ flex: 1, minWidth: 0 }}>
                        <Typography variant="body2" fontWeight={600} noWrap>{c.name}</Typography>
                        <Typography variant="caption" color="text.secondary" noWrap>{formatCurrency(c.totalSpent)} spent</Typography>
                      </Box>
                      <Button size="small" variant="outlined" onClick={() => handlePreview(c)}
                        sx={{ fontSize: '0.7rem', px: 1, py: 0.4, flexShrink: 0 }}
                        startIcon={<VisibilityRounded sx={{ fontSize: '14px !important' }} />}>
                        Preview
                      </Button>
                    </Box>
                  ))}
                </Box>
              </CardContent>
            </Card>
          )}
        </Grid>

        {/* RIGHT — Live progress + Results */}
        <Grid item xs={12} lg={7}>

          {/* Live step log */}
          {(running || steps.length > 0) && (
            <Card sx={{ mb: 2.5 }}>
              <CardContent sx={{ p: 2.5 }}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                  {running && <CircularProgress size={16} sx={{ color: 'primary.main' }} />}
                  <Typography variant="subtitle1" fontWeight={700}>
                    {running ? 'AI is working…' : 'Campaign Complete'}
                  </Typography>
                </Box>

                {running && (
                  <LinearProgress sx={{ mb: 2, borderRadius: 2, height: 6 }} />
                )}

                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                  {steps.map((step, i) => (
                    <Box key={step.id} sx={{ display: 'flex', gap: 1.5, alignItems: 'flex-start' }}>
                      <Box sx={{ flexShrink: 0, mt: 0.3 }}>
                        {step.status === 'running' && <CircularProgress size={16} sx={{ color: 'primary.main' }} />}
                        {step.status === 'done' && <CheckCircleRounded sx={{ fontSize: 18, color: 'success.main' }} />}
                        {step.status === 'error' && <ErrorRounded sx={{ fontSize: 18, color: 'error.main' }} />}
                      </Box>
                      <Box sx={{ flex: 1 }}>
                        <Typography variant="body2" fontWeight={step.status === 'running' ? 700 : 500}
                          color={step.status === 'error' ? 'error.main' : step.status === 'done' ? 'text.primary' : 'text.primary'}>
                          {step.label}
                        </Typography>
                        {step.detail && (
                          <Typography variant="caption" color={step.status === 'error' ? 'error.main' : step.status === 'done' ? 'success.main' : 'text.secondary'}>
                            {step.detail}
                          </Typography>
                        )}
                      </Box>
                    </Box>
                  ))}
                </Box>
              </CardContent>
            </Card>
          )}

          {/* Results */}
          {result && (
            <>
              {/* Summary cards */}
              <Grid container spacing={2} sx={{ mb: 2.5 }}>
                {[
                  { label: 'Total Reached', val: result.summary.total, icon: <PeopleRounded />, color: '#5B4CF5' },
                  { label: 'Delivered', val: result.summary.delivered, icon: <MarkEmailReadRounded />, color: '#22C55E' },
                  { label: 'Real Emails Sent', val: result.summary.realEmailsSent, icon: <EmailRounded />, color: '#3B82F6' },
                  { label: 'Failed', val: result.summary.failed, icon: <ErrorRounded />, color: '#EF4444' },
                ].map((m, i) => (
                  <Grid item xs={6} sm={3} key={i}>
                    <Card sx={{ border: `1px solid ${m.color}22` }}>
                      <CardContent sx={{ p: 1.5, textAlign: 'center' }}>
                        <Box sx={{ color: m.color, mb: 0.5, '& .MuiSvgIcon-root': { fontSize: 20 } }}>{m.icon}</Box>
                        <Typography variant="h5" fontWeight={800} sx={{ color: m.color }}>{m.val}</Typography>
                        <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.68rem' }}>{m.label}</Typography>
                      </CardContent>
                    </Card>
                  </Grid>
                ))}
              </Grid>

              {/* Per-customer results */}
              <Card>
                <CardContent sx={{ p: 2.5 }}>
                  <Typography variant="subtitle1" fontWeight={700} mb={2}>
                    🤖 AI-Generated Offers ({result.results.length})
                  </Typography>
                  <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
                    {result.results.map((r, i) => (
                      <Box
                        key={i}
                        sx={{
                          p: 2, border: '1px solid', borderColor: r.status === 'Failed' ? 'error.main' : 'divider',
                          borderRadius: 2.5, bgcolor: r.status === 'Failed' ? 'rgba(239,68,68,0.04)' : 'background.default',
                          cursor: r.offerCode ? 'pointer' : 'default',
                          '&:hover': r.offerCode ? { borderColor: 'primary.main', bgcolor: 'rgba(91,76,245,0.04)' } : {},
                          transition: 'all 0.15s'
                        }}
                        onClick={() => r.offerCode && setOfferDialog(r)}
                      >
                        <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5 }}>
                          <Avatar sx={{ width: 34, height: 34, fontSize: '0.85rem', fontWeight: 800, bgcolor: AVATAR_COLORS[i % AVATAR_COLORS.length], flexShrink: 0 }}>
                            {r.customerName?.charAt(0)}
                          </Avatar>
                          <Box sx={{ flex: 1, minWidth: 0 }}>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap', mb: 0.3 }}>
                              <Typography variant="body2" fontWeight={700}>{r.customerName}</Typography>
                              <Chip
                                label={r.status === 'Failed' ? '✗ Failed' : r.emailSent ? '✓ Email Sent' : '✓ Simulated'}
                                size="small"
                                sx={{
                                  height: 20, fontSize: '0.65rem', fontWeight: 700,
                                  bgcolor: r.status === 'Failed' ? 'rgba(239,68,68,0.12)' : r.emailSent ? 'rgba(34,197,94,0.12)' : 'rgba(59,130,246,0.12)',
                                  color: r.status === 'Failed' ? '#EF4444' : r.emailSent ? '#22C55E' : '#3B82F6'
                                }}
                              />
                            </Box>
                            {r.offerCode && (
                              <>
                                <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.72rem', display: 'block' }} noWrap>
                                  📧 {r.subject}
                                </Typography>
                                <Box sx={{ display: 'flex', gap: 1, mt: 0.5, flexWrap: 'wrap', alignItems: 'center' }}>
                                  <Chip label={r.offerCode} size="small" sx={{ height: 20, fontSize: '0.68rem', fontWeight: 800, bgcolor: 'rgba(91,76,245,0.1)', color: 'primary.main' }} />
                                  <Chip label={`${r.discountPercent}% OFF`} size="small" sx={{ height: 20, fontSize: '0.68rem', fontWeight: 700, bgcolor: 'rgba(34,197,94,0.1)', color: 'success.main' }} />
                                  <Typography variant="caption" color="text.disabled" sx={{ fontSize: '0.65rem' }}>tap to view full offer</Typography>
                                </Box>
                              </>
                            )}
                            {r.error && (
                              <Typography variant="caption" color="error.main" sx={{ fontSize: '0.7rem' }}>{r.error}</Typography>
                            )}
                          </Box>
                        </Box>
                      </Box>
                    ))}
                  </Box>
                </CardContent>
              </Card>
            </>
          )}

          {/* Placeholder when nothing running */}
          {!running && !result && steps.length === 0 && (
            <Card sx={{ height: 400, display: 'flex', alignItems: 'center', justifyContent: 'center', border: '2px dashed', borderColor: 'divider' }}>
              <Box sx={{ textAlign: 'center', p: 4 }}>
                <Box sx={{ fontSize: '3.5rem', mb: 2 }}>🤖</Box>
                <Typography variant="h6" fontWeight={700} mb={1}>Ready to launch</Typography>
                <Typography variant="body2" color="text.secondary" maxWidth={320}>
                  Select an audience segment on the left and click <strong>Generate & Send AI Campaign</strong>. Gemini will read each customer's data and write a unique personalized offer for them.
                </Typography>
              </Box>
            </Card>
          )}
        </Grid>
      </Grid>

      {/* Preview Dialog */}
      <Dialog open={previewOpen} onClose={() => setPreviewOpen(false)} maxWidth="sm" fullWidth PaperProps={{ sx: { borderRadius: 3 } }}>
        <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', pb: 1 }}>
          <Box>
            <Typography variant="h6" fontWeight={700}>AI Offer Preview</Typography>
            <Typography variant="caption" color="text.secondary">
              What Gemini would generate for {previewCustomer?.name}
            </Typography>
          </Box>
          <IconButton size="small" onClick={() => setPreviewOpen(false)}><CloseRounded /></IconButton>
        </DialogTitle>
        <DialogContent>
          {previewLoading ? (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, py: 2 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
                <CircularProgress size={20} />
                <Typography variant="body2" color="text.secondary">Gemini is reading {previewCustomer?.name}'s data…</Typography>
              </Box>
              {Array(4).fill(0).map((_, i) => <Skeleton key={i} height={18} sx={{ borderRadius: 1 }} />)}
            </Box>
          ) : previewData ? (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, py: 1 }}>
              {/* Subject */}
              <Box sx={{ p: 1.5, bgcolor: 'primary.main', borderRadius: 2, color: 'white' }}>
                <Typography variant="caption" sx={{ opacity: 0.8, textTransform: 'uppercase', letterSpacing: '0.08em' }}>Email Subject</Typography>
                <Typography variant="body1" fontWeight={700} mt={0.3}>{previewData.offer.subject}</Typography>
              </Box>

              {/* Offer code */}
              <Box sx={{ display: 'flex', gap: 2 }}>
                <Box sx={{ flex: 1, p: 1.5, border: '2px dashed', borderColor: 'primary.main', borderRadius: 2, textAlign: 'center', bgcolor: 'rgba(91,76,245,0.04)' }}>
                  <Typography variant="caption" color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.06em' }}>Offer Code</Typography>
                  <Typography variant="h5" fontWeight={900} color="primary.main" mt={0.3}>{previewData.offer.offerCode}</Typography>
                </Box>
                <Box sx={{ flex: 1, p: 1.5, border: '1px solid', borderColor: 'success.main', borderRadius: 2, textAlign: 'center', bgcolor: 'rgba(34,197,94,0.04)' }}>
                  <Typography variant="caption" color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.06em' }}>Discount</Typography>
                  <Typography variant="h5" fontWeight={900} color="success.main" mt={0.3}>{previewData.offer.discountPercent}% OFF</Typography>
                </Box>
              </Box>

              {/* Message */}
              <Box sx={{ p: 1.5, bgcolor: 'action.hover', borderRadius: 2 }}>
                <Typography variant="caption" color="text.secondary" fontWeight={600} sx={{ textTransform: 'uppercase', letterSpacing: '0.06em', display: 'block', mb: 0.5 }}>
                  Personalized Message
                </Typography>
                <Typography variant="body2" sx={{ lineHeight: 1.7, fontStyle: 'italic' }}>"{previewData.offer.offerMessage}"</Typography>
              </Box>

              {/* Customer profile */}
              <Box sx={{ p: 1.5, border: '1px solid', borderColor: 'divider', borderRadius: 2 }}>
                <Typography variant="caption" color="text.secondary" fontWeight={600} sx={{ textTransform: 'uppercase', letterSpacing: '0.06em', display: 'block', mb: 1 }}>
                  Customer Data AI Read
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                  {[
                    { label: 'City', val: previewData.offer.customerProfile?.city },
                    { label: 'Total Spent', val: formatCurrency(previewData.offer.customerProfile?.totalSpent) },
                    { label: 'Orders', val: previewData.offer.customerProfile?.totalOrders },
                    { label: 'Top Categories', val: previewData.offer.customerProfile?.topCategories?.join(', ') || '—' },
                  ].map((f, i) => (
                    <Box key={i} sx={{ px: 1.2, py: 0.6, bgcolor: 'background.default', borderRadius: 1.5, border: '1px solid', borderColor: 'divider' }}>
                      <Typography variant="caption" color="text.secondary" sx={{ fontSize: '0.65rem', textTransform: 'uppercase', display: 'block' }}>{f.label}</Typography>
                      <Typography variant="caption" fontWeight={700} sx={{ fontSize: '0.75rem' }}>{f.val}</Typography>
                    </Box>
                  ))}
                </Box>
              </Box>
            </Box>
          ) : null}
        </DialogContent>
        <DialogActions sx={{ p: 2 }}>
          <Button onClick={() => setPreviewOpen(false)}>Close</Button>
          {previewData && (
            <Button variant="contained" onClick={() => { setPreviewOpen(false); setSelectedSegment(selectedSegment || segments[0]); }}>
              Launch Full Campaign
            </Button>
          )}
        </DialogActions>
      </Dialog>

      {/* Full offer detail dialog */}
      <Dialog open={!!offerDialog} onClose={() => setOfferDialog(null)} maxWidth="md" fullWidth PaperProps={{ sx: { borderRadius: 3 } }}>
        <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Box>
            <Typography variant="h6" fontWeight={700}>Offer sent to {offerDialog?.customerName}</Typography>
            <Typography variant="caption" color="text.secondary">{offerDialog?.customerEmail}</Typography>
          </Box>
          <IconButton size="small" onClick={() => setOfferDialog(null)}><CloseRounded /></IconButton>
        </DialogTitle>
        <DialogContent>
          {offerDialog && (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <Box sx={{ p: 1.5, bgcolor: 'primary.main', borderRadius: 2, color: 'white' }}>
                <Typography variant="caption" sx={{ opacity: 0.8 }}>Subject Line</Typography>
                <Typography variant="body1" fontWeight={700}>{offerDialog.subject}</Typography>
              </Box>
              <Box sx={{ display: 'flex', gap: 2 }}>
                <Box sx={{ flex: 1, p: 1.5, border: '2px dashed', borderColor: 'primary.main', borderRadius: 2, textAlign: 'center' }}>
                  <Typography variant="caption" color="text.secondary">Offer Code</Typography>
                  <Typography variant="h5" fontWeight={900} color="primary.main">{offerDialog.offerCode}</Typography>
                </Box>
                <Box sx={{ flex: 1, p: 1.5, border: '1px solid', borderColor: 'success.main', borderRadius: 2, textAlign: 'center' }}>
                  <Typography variant="caption" color="text.secondary">Discount</Typography>
                  <Typography variant="h5" fontWeight={900} color="success.main">{offerDialog.discountPercent}% OFF</Typography>
                </Box>
              </Box>
              <Box sx={{ p: 1.5, bgcolor: 'action.hover', borderRadius: 2 }}>
                <Typography variant="caption" color="text.secondary" fontWeight={600} display="block" mb={0.5}>Personalized Message</Typography>
                <Typography variant="body2" sx={{ fontStyle: 'italic', lineHeight: 1.7 }}>"{offerDialog.message}"</Typography>
              </Box>
              <Box sx={{ display: 'flex', gap: 1 }}>
                <Chip label={offerDialog.emailSent ? '✓ Real Email Sent' : '✓ Simulated'} sx={{ bgcolor: offerDialog.emailSent ? 'rgba(34,197,94,0.12)' : 'rgba(59,130,246,0.12)', color: offerDialog.emailSent ? 'success.main' : 'info.main', fontWeight: 700 }} />
                <Chip label={`Status: ${offerDialog.status}`} sx={{ bgcolor: 'rgba(91,76,245,0.1)', color: 'primary.main', fontWeight: 700 }} />
              </Box>
            </Box>
          )}
        </DialogContent>
        <DialogActions sx={{ p: 2 }}>
          <Button onClick={() => setOfferDialog(null)}>Close</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

function delay(ms) { return new Promise(r => setTimeout(r, ms)); }
